import type { Metadata } from 'next'
import '../styles/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&icon_names=arrow_upward"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&icon_names=close"
        />
        <script async src="https://connect.facebook.net/en_US/fbevents.js">
          {`
            window.fbq = function() {
                fbq.callMethod ? fbq.callMethod.apply(fbq, arguments) : fbq.queue.push(arguments);
                };
            if (!window._fbq) window._fbq = fbq;
            fbq.push = fbq;
            fbq.loaded = true;
            fbq.version = '2.0';
            fbq.queue = [];
            fbq('init', '928015015669565');
            fbq('track', 'PageView');
            `}
        </script>
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-BCX2BREJ96" />
        <script>
          {`
            window.dataLayer = window.dataLayer || [];
                function gtag(...args) {
                    dataLayer.push(args);
            }
            gtag('js', new Date());
            gtag('config', 'G-BCX2BREJ96');
                `}
        </script>
        <link rel="icon" type="image/svg+xml" href="./favicon.ico" />
        <link rel="apple-touch-icon" type="image/svg+xml" href="./favicon.ico" />
        <meta name="robots" content="index, follow" />
        <title>Mariella Giacon - Arquitetura Paisagística</title>
        <link rel="manifest" href="manifest.json" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="application-name" content="Mariella Giacon" />
        <meta name="apple-mobile-web-app-title" content="Mariella Giacon" />
        <meta name="theme-color" content="#CDE3CA" />
        <meta name="msapplication-navbutton-color" content="#CDE3CA" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        <meta name="msapplication-starturl" content="/" />
        <meta
          name="google-site-verification"
          content="pGOzcfoiqWHQqYh_FHc7rV1WS_XhxL7TlhBxKRDLF9M"
        />
        <meta name="og:type" content="website" />
        <meta name="og:image" content="/assets/icons/mariella.png" />
        <meta property="og:image:width" content="500" />
        <meta property="og:image:height" content="500" />
        <meta property="og:image:alt" content="Logo Mariella Giacon paisagismo" />
        <meta name="og:url" content="https://mariellagiacon.com.br" />
        <meta name="og:title" content="Mariella Giacon - Arquitetura Paisagística" />
        <meta
          name="og:description"
          content="Arquitetura paisagística sustentável em Limeira. Projetos personalizados, assessoria e execução de jardins com plantas nativas."
        />
        <meta name="og:site_name" content="Mariella Giacon - Arquitetura Paisagística" />

        <meta
          name="keywords"
          content="mariella, giacon, limeira, sp, arquitetura, paisagistica, mariella giacon paisagista, mariella giacon arquitetura, aruitetura paisagistica, mariella giacon, arquitetura paisagistica em limeira sp, arquiteto limeira, paisagista limeira, arquitetura paisagistica limeira, paisagismo sustentavel, projetos de jardins, acessoria de jardins, assinatura de vasos, curadoria de moveis, jardim vertical, acompanhamento de obra"
        />
        <meta
          name="description"
          content="Arquitetura paisagística sustentável em Limeira. Projetos personalizados, assessoria e execução de jardins com plantas nativas."
        />
        <meta name="twitter:card" content="summary" />
        <meta name="twitter:image" content="/assets/icons/mariella.png" />
        <meta name="twitter:image:alt" content="Logo Mariella Giacon paisagismo" />
        <meta name="twitter:title" content="Mariella Giacon - Arquitetura Paisagística" />
        <meta
          name="twitter:description"
          content="Arquitetura paisagística sustentável em Limeira. Projetos personalizados, assessoria e execução de jardins com plantas nativas."
        />
      </head>
      <body>{children}</body>
    </html>
  )
}
